server.port=1234

# ===============================
# DATASOURCE
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/financeall
spring.datasource.username=postgres
spring.datasource.password=Alfarizi
# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# THYMELEAF
# ===============================

spring.thymeleaf.cache=false

# ===============================
# LOGGING
# ===============================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE